### ISSUE TITLE
PKGBUILDs should not be using `pip install`

### ISSUE THREAD

**Issue by Kwpolska** [bartoszek/AUR-meshroom#2]
The PKGBUILDs for `meshroom` and `meshroom-git` are dangerous and incorrect.

1. The `pip install --user` call means the software is unusable in multi-user environments.
2. `pip install` can override or remove user-installed packages. Bad dependencies can break many parts of the system. Your PKGBUILD overrides `requests`, which is also a `pip` dependency. If the version installed by your PKGBUILD does not match the system-installed version, `pip` might stop working, since it’s expecting a different version.
3. Running `makepkg` should never introduce changes to the system as part of the PKGBUILD. If you don’t install the package, the system should look the same as before building it.
4. If software is not compatible with some dependencies, it is your duty as the AUR maintainer to fix it in this specific software, either by [contributing a fix upstream](https://wiki.archlinux.org/index.php/Arch_package_guidelines#Working_with_upstream), or adding a patch to the AUR package.
5. A package for `meshroom` should include `meshroom` only.
6. While using `pip` is possible (but discouraged), you would have to follow [some specific rules](https://wiki.archlinux.org/index.php/Python_package_guidelines#pip) when running it, and again, it should not be used to install dependencies, because 1 Python package = 1 AUR package.

**Comment by sandsmark** [comment]
it runs completely fine just removing the pip line

**Comment by bartoszek** [comment]
@Kwpolska Yep, you have a valid point here. It was just a temporary fix cbab9982af60576e71faed7eaaf30193bf1bb05d for broken `pyside` in `community`. I always build packages in `tmp/chroot` so it doesn't effect my machine, will fix this.
