### ISSUE TITLE
hardcoded path to camera DB is wrong

### ISSUE THREAD

**Issue by sandsmark** [bartoszek/AUR-meshroom#4]
`/usr/share/aliceVision/sensor_width_camera_database.txt` doesn't exist after installing, however /usr/share/aliceVision/cameraSensors.db does, which is the default you patch away with sed

removing lines 31 and 32 in the PKGBUILD makes it work

**Comment by bartoszek** [comment]
@sandsmark sorry for delay.

**Comment by sandsmark** [comment]
no problem, it was easy to patch out manually. :-)
