### ISSUE TITLE
don't bundle extra qt image plugins

### ISSUE THREAD

**Issue by sandsmark** [bartoszek/AUR-meshroom#5]
QtOIIO isn't even a dependency (as far as I can see), so why is it built and bundled inside this package?

**Comment by ChemicalXandco** [comment]
QtOIIO is a dependency please see https://github.com/alicevision/meshroom/blob/develop/INSTALL.md

**Comment by sandsmark** [comment]
it just provides support for more image formats in all Qt applications, like any `QImageIOPlugin`.

e. g. `kimageformats` in `extra` already provides EXR support (and the official `qt5-imageformats` contains a bunch, like tiff and tga), so there's no point in adding it as a hard dependency to this package. there's also `qtraw` in AUR that I'm fairly certain has better support than QtOIIO.

it's a completely separate thing, it just happens to be developed by the same people.
